#!/bin/bash
#PBS -N poisson_4096_4_9
#PBS -l select=4:ncpus=9:mpiprocs=4
#PBS -l walltime=00:01:30

module load GCC OpenMPI

cd $PBS_O_WORKDIR

mpirun ./poisson 16384

# Append the job statistics to the std out file
qstat -f $PBS_JOBID
