#!/bin/bash
#PBS -N poisson_16384_4_8
#PBS -l select=4:ncpus=8:mpiprocs=1
#PBS -l walltime=00:05:00

module load GCC OpenMPI

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=8
mpirun ./poisson 16384

# Append the job statistics to the std out file
qstat -f $PBS_JOBID
